# Generated by Django 2.0.5 on 2020-10-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('principalname', models.CharField(max_length=100)),
                ('principalno', models.CharField(max_length=20)),
                ('los', models.CharField(max_length=100)),
            ],
        ),
    ]
